include(../modules/PathUtils.cmake)

function (test_abs _base _path _expect)
    get_abs_path(_res "${_path}" BASE "${_base}")

    if ("XXX_${_res}" STREQUAL "XXX_${_expect}")
        message(STATUS "Checking get_abs_path() for '${_path}' with base '${_base}': OK")
    else ()
        message(SEND_ERROR "Checking get_abs_path() for '${_path}' with base '${_base}': FAILED, got '${_res}', expected '${_expect}'")
    endif ()
endfunction ()

function (test_rel _dir _file _expect)
    get_rel_path(_res "${_dir}" "${_file}")

    if ("XXX_${_res}" STREQUAL "XXX_${_expect}")
        message(STATUS "Checking get_rel_path() for '${_file}' relative to '${_dir}': OK")
    else ()
        message(SEND_ERROR "Checking get_rel_path() for '${_file}' relative to '${_dir}': FAILED, got '${_res}', expected '${_expect}'")
    endif ()
endfunction ()

test_abs("/usr/include" "test" "/usr/include/test")
test_abs("/usr/include" "../test" "/usr/test")
test_abs("/usr/include" "../../test" "/test")
test_abs("/usr/include" "../../../test" "/test")
test_abs("/usr/include" "../../../../test" "/test")
test_abs("/usr/include/.." "test" "/usr/test")
test_abs("/usr/include" "test/.." "/usr/include")
test_abs("/usr/include/.." "../test" "/test")
test_abs("/usr/include/.." "." "/usr")
test_abs("/usr/include/.." ".." "/")
test_abs("/usr/include/.." "../.." "/")

test_rel("/usr/include" "/usr/include/test" "test")
test_rel("/usr/include" "/usr/test" "../test")
test_rel("/usr/include" "/var/test" "../../var/test")
test_rel("/usr/include" "/usr/include/../test" "../test")
test_rel("/usr/include" "/usr/../usr/include/test" "test")
test_rel("/usr/include/.." "/usr/include/test" "include/test")
test_rel("/usr/share/.." "/usr/include/test" "include/test")
